In [1]:
with open('./dataset/imdb_trainX.txt',encoding="utf-8") as file:
    reviews = file.readlines()
    print(type(reviews))
with open('./dataset/imdb_trainY.txt',encoding="utf8") as f:
    y = f.readlines()
print(int(y[100]))

<class 'list'>
10


In [2]:
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
from nltk.stem.snowball import PorterStemmer
import numpy as np

In [3]:
reviews[0]=reviews[0].replace("<br /><br /"," ")
tokenizer = RegexpTokenizer(r'\w+')
tokenized_words = tokenizer.tokenize(reviews[0].lower())
tokenized_words

['i',
 'loved',
 'this',
 'movie',
 'since',
 'i',
 'was',
 '7',
 'and',
 'i',
 'saw',
 'it',
 'on',
 'the',
 'opening',
 'day',
 'it',
 'was',
 'so',
 'touching',
 'and',
 'beautiful',
 'i',
 'strongly',
 'recommend',
 'seeing',
 'for',
 'all',
 'it',
 's',
 'a',
 'movie',
 'to',
 'watch',
 'with',
 'your',
 'family',
 'by',
 'far',
 'my',
 'mpaa',
 'rating',
 'pg',
 '13',
 'for',
 'thematic',
 'elements',
 'prolonged',
 'scenes',
 'of',
 'disastor',
 'nudity',
 'sexuality',
 'and',
 'some',
 'language']

In [4]:
sw = set(stopwords.words('english'))

In [5]:
clean_words = [w for w in tokenized_words if w not in sw]
clean_words

['loved',
 'movie',
 'since',
 '7',
 'saw',
 'opening',
 'day',
 'touching',
 'beautiful',
 'strongly',
 'recommend',
 'seeing',
 'movie',
 'watch',
 'family',
 'far',
 'mpaa',
 'rating',
 'pg',
 '13',
 'thematic',
 'elements',
 'prolonged',
 'scenes',
 'disastor',
 'nudity',
 'sexuality',
 'language']

In [6]:
ps = PorterStemmer()
stemmed_words = []
for w in clean_words:
    stemmed_words.append(ps.stem(w))
clean_words = ' '.join(stemmed_words)
clean_words

    

'love movi sinc 7 saw open day touch beauti strongli recommend see movi watch famili far mpaa rate pg 13 themat element prolong scene disastor nuditi sexual languag'

In [7]:
import data_cleaner as dc

In [14]:
rev_test = reviews[10:210]
clean_test = [dc.clean_text(w) for w in rev_test]
reviews_train = reviews[:1000]
cleaned_data = [dc.clean_text(r) for r in reviews_train]
y = [int(i) for i in y]
Y = y[:1000]
Y = np.array(Y)
Y_test = np.array(y[10:210])

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv = CountVectorizer()

In [20]:
X = cv.fit_transform(cleaned_data).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
X_test = cv.transform(clean_test).toarray()
X_test.shape

(200, 13242)

In [44]:
from sklearn.naive_bayes import MultinomialNB

In [45]:
mnb = MultinomialNB()

In [46]:
mnb.fit(X,Y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [47]:
mnb.predict(X_test)

array([ 8,  8, 10,  8,  8,  8, 10, 10,  7,  7,  8, 10,  8,  9,  8, 10, 10,
       10,  7,  9,  9,  7, 10, 10, 10, 10,  7,  9, 10,  9, 10,  9, 10,  8,
        8, 10,  8, 10,  8,  8,  8,  7,  8,  8,  7,  7, 10, 10,  7, 10,  7,
        9, 10,  8,  7, 10, 10, 10,  7, 10, 10, 10,  8, 10, 10, 10, 10,  8,
       10, 10,  9,  9,  8,  8,  9,  7,  9, 10, 10,  7,  7, 10, 10,  7,  7,
       10,  8,  8, 10, 10, 10,  7, 10,  8, 10,  8,  8,  8,  9,  8, 10, 10,
       10, 10,  7, 10, 10, 10, 10, 10, 10, 10, 10,  8,  8,  8,  8,  8, 10,
       10, 10, 10,  8,  8,  8,  7, 10,  7, 10, 10,  8, 10,  9,  9, 10,  7,
        9, 10,  8, 10,  8,  7,  8, 10,  7,  8, 10, 10, 10, 10, 10,  9,  9,
       10,  8, 10, 10, 10, 10,  9, 10, 10, 10, 10, 10,  9,  7, 10, 10,  7,
       10,  7,  8, 10,  7,  7, 10, 10, 10, 10,  8,  9,  8, 10, 10,  7, 10,
        9, 10, 10,  9, 10, 10, 10, 10,  7,  7,  7, 10, 10])

In [48]:
Y_test

array([ 8,  8, 10,  8,  8,  8,  9, 10,  7,  7,  8,  7,  8,  9,  8,  7, 10,
       10,  7,  9,  9,  7, 10, 10, 10, 10,  7,  9, 10,  9, 10,  9, 10,  8,
        8, 10,  8, 10,  8,  8,  8,  7,  8,  8,  7,  7, 10, 10,  7, 10,  7,
        9, 10,  8,  7, 10, 10, 10,  7, 10, 10,  8,  8,  8, 10, 10, 10,  8,
       10, 10,  9,  9,  8,  8,  9,  7,  9, 10, 10,  7,  7, 10, 10,  7,  7,
       10,  8,  8, 10, 10, 10,  7, 10,  8, 10,  8,  8,  8,  9,  8, 10, 10,
        9, 10,  7, 10, 10, 10,  8, 10, 10, 10, 10,  8,  8,  8,  8,  8, 10,
       10, 10, 10,  8,  8,  8,  7, 10,  7, 10, 10,  8, 10,  9,  9, 10,  7,
        9, 10,  8,  9,  8,  7,  8, 10,  7,  8, 10, 10, 10, 10, 10,  9,  9,
       10,  8, 10, 10, 10, 10,  9,  8, 10, 10,  7,  9,  9,  7, 10, 10,  7,
       10,  7,  8, 10,  7,  7, 10, 10, 10, 10,  8,  9,  8, 10, 10,  7, 10,
        9, 10,  8,  9, 10, 10,  7,  8,  7,  7,  7, 10,  7])

In [49]:
mnb.score(X,Y)

0.924

In [50]:
clean_test[2]

'definit great movi want continu see movi reason strike cord even though scene scott glenn still make winch watch love music'

In [51]:
np.unique(Y)

array([ 7,  8,  9, 10])